source "https://rubygems.org"

ruby '2.3.0'

gem 'bundler'
gem 'jekyll'

gem 'rack-jekyll'
gem 'rake'
gem 'rspec'
gem 'kramdown'

gem 'jekyll-auth'

gem "execjs"
gem "therubyracer"

gem "github-pages", group: :jekyll_plugins

# If you want to use Jekyll native, uncomment the line below.
# To upgrade, run `bundle update`.

# gem "jekyll"

gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-archives"
end
